site_name: Flink Project Demonstrations
repo_url: https://github.com/jbcodeforce/flink_project_demos
site_url: https://jeromeboyer.net/flink_project_demos
copyright: Copyright &copy; 2025 Jerome Boyer
nav:
  - Introduction: index.md
  - Design:
    - Customer 360 Data Model: c360/data_models.md
  - Implementations:
    - C360 Spark Project: c360/spark_project.md
    - Automatic Migration: automatic_migration.md
    - C360 Flink Project: c360/flink_project.md
  - External References:
    - Spark SQL best practices: https://jbcodeforce.github.io/spark-studies/
    - Flink SQL best practices: https://jbcodeforce.github.io/flink-studies/coding/flink-sql/

theme: 
  name: material
  logo: assets/batchy.png
  favicon: assets/batchy.png
  palette:
    scheme: default
  language: en
  features:
      - content.code.annotate
      - content.code.copy
      - content.tooltips
      - content.tabs.link
      - search.suggest
      - search.highlight
      - navigation.instant
      - navigation.instant.progress
      #- navigation.tabs
      - navigation.tabs.sticky
      - navigation.tracking
      - navigation.sections
      - navigation.expand
      - navigation.top
      - navigation.footer

extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - mkdocstrings

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - tables
  #- pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.smartsymbols
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/jbcodeforce'
    - icon: fontawesome/brands/linkedin
      link: 'https://linkedin.com/in/jeromeboyer'
    - icon: fontawesome/solid/paper-plane
      mailto: jerome@intelligent-automations.com