CREATE TABLE IF NOT EXISTS george_martin (
  ",
  " `author` STRING,
  ",
  " `title` STRING,
  ",
  " `publication_date` TIMESTAMP(3),
  ",
  " `genre` STRING,
  ",
  " `pages` BIGINT,
  ",
  " `isbn` STRING,
  ",
  " PRIMARY KEY (`isbn`) NOT ENFORCED ",
  "
) DISTRIBUTED BY HASH(`isbn`) INTO 1 BUCKETS WITH (
  ",
  " 'changelog.mode' = 'append',
  ",
  " 'kafka.retention.time' = '0',
  ",
  " 'kafka.producer.compression.type' = 'snappy',
  ",
  " 'scan.bounded.mode' = 'unbounded',
  ",
  " 'scan.startup.mode' = 'earliest-offset',
  ",
  " 'value.fields-include' = 'all' ",
  "
);

",
" ",
" CREATE TABLE IF NOT EXISTS all_publications (
  ",
  " `author` STRING,
  ",
  " `title` STRING,
  ",
  " `publication_date` TIMESTAMP(3),
  ",
  " `genre` STRING,
  ",
  " `pages` BIGINT,
  ",
  " `isbn` STRING,
  ",
  " PRIMARY KEY (`isbn`) NOT ENFORCED ",
  "
) DISTRIBUTED BY HASH(`isbn`) INTO 1 BUCKETS WITH (
  ",
  " 'changelog.mode' = 'append',
  ",
  " 'kafka.retention.time' = '0',
  ",
  " 'kafka.producer.compression.type' = 'snappy',
  ",
  " 'scan.bounded.mode' = 'unbounded',
  ",
  " 'scan.startup.mode' = 'earliest-offset',
  ",
  " 'value.fields-include' = 'all' ",
  "
);